version = 0.1
[dev.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=\"dev\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "sam-app-prod"
resolve_s3 = true
s3_prefix = "sam-app-prod"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvType=\"prod\""
image_repositories = []
